const ACTION__SET_ENTITY = 'ACTION__SET_ENTITY';
const ACTION__RESET_ENTITY = 'ACTION__RESET_ENTITY';
const ACTION__SET_TYPE = 'ACTION__SET_TYPE';
const ACTION__RESET_TYPE = 'ACTION__RESET_TYPE';
const ACTION__SET_ID = 'ACTION__SET_ID';
const ACTION__RESET_ID = 'ACTION__RESET_ID';


export default {
	ACTION__SET_ENTITY,
	ACTION__RESET_ENTITY,
	ACTION__SET_TYPE,
	ACTION__RESET_TYPE,
	ACTION__SET_ID,
	ACTION__RESET_ID,
};
