const ACTION__ADD_PARTICIPANT = 'ACTION__ADD_PARTICIPANT';
const ACTION__REMOVE_PARTICIPANT = 'ACTION__REMOVE_PARTICIPANT';
const ACTION__REQUEST_TRADE_SUCCESS = 'ACTION__REQUEST_TRADE_SUCCESS';
const ACTION__UPDATE_AVENUE = 'ACTION__UPDATE_AVENUE';


export default {
	ACTION__ADD_PARTICIPANT,
	ACTION__REMOVE_PARTICIPANT,
	ACTION__REQUEST_TRADE_SUCCESS,
	ACTION__UPDATE_AVENUE,
};
